In [17]:
from bs4 import BeautifulSoup
from urllib.request import urlopen

url = 'https://www.iplt20.com/stats/2021/mostRuns?stats_type=batting'
web = urlopen(url)
source = BeautifulSoup(web, 'html.parser')

table = source.find('table', class_='np-mostruns_table')
headers = []
for i in table.find_all('th'):
    title = i.text
    headers.append(title)

In [18]:
headers

['POS',
 'Player',
 'Mat',
 'Inns',
 'NO',
 'Runs',
 'HS',
 'Avg',
 'BF',
 'SR',
 '100',
 '50',
 '4s',
 '6s']

In [36]:
table_rows = table.find_all('tr')[1:]
l = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [str(tr.get_text()).strip() for tr in td]
    l.append(row)

batting_stats = pd.DataFrame(l, columns=headers)
batting_stats

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
0,1,Ruturaj Gaikwad,16,16,2,635,101,45.35,466,136.26,1,4,64,23
1,2,Faf du Plessis,16,16,2,633,95,45.21,458,138.20,0,6,60,23
2,3,KL Rahul,13,13,3,626,98,62.60,451,138.80,0,6,48,30
3,4,Shikhar Dhawan,16,16,1,587,92,39.13,471,124.62,0,3,63,16
4,5,Glenn Maxwell,15,14,2,513,78,42.75,356,144.10,0,6,48,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,145,Kuldip Yadav,1,1,1,0,0,0.00,4,0.00,0,0,0,0
145,146,Sarfaraz Khan,2,2,0,0,0,0.00,4,0.00,0,0,0,0
146,147,Anuj Rawat,2,1,0,0,0,0.00,1,0.00,0,0,0,0
147,148,Jimmy Neesham,3,2,0,0,0,0.00,2,0.00,0,0,0,0
148,149,Piyush Chawla,1,1,0,0,0,0.00,2,0.00,0,0,0,0

In [33]:
batting_stats.to_csv('batting_stats.csv', index=False)