In [2]:
from bs4 import BeautifulSoup 
from urllib.request import urlopen
import pandas as pd

url = 'https://www.iplt20.com/stats/2021/mostWkts?stats_type=bowling'
web = urlopen(url)
soup = BeautifulSoup(web, 'html.parser')

table = soup.find_all('table')[1]
headers = []
for i in table.find_all('th'):
    title = i.text
    headers.append(title)

In [3]:
headers

['POS',
 'Player',
 'Mat',
 'Inns',
 'Ov',
 'Runs',
 'Wkts',
 'BBI',
 'Avg',
 'Econ',
 'SR',
 '4w',
 '5w']

In [4]:
table_rows = table.find_all('tr')[1:]
l = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [str(tr.get_text()).strip() for tr in td]
    l.append(row)

bowling_stats = pd.DataFrame(l, columns=headers)
bowling_stats

,POS,Player,Mat,Inns,Ov,Runs,Wkts,BBI,Avg,Econ,SR,4w,5w
0,1,Harshal Patel,15,15,56.2,459,32,5/27,14.34,8.14,10.56,1,1
1,2,Avesh Khan,16,16,61,450,24,3/13,18.75,7.37,15.25,0,0
2,3,Jasprit Bumrah,14,14,55,410,21,3/36,19.52,7.45,15.71,0,0
3,4,Shardul Thakur,16,16,59.5,527,21,3/28,25.09,8.80,17.09,0,0
4,5,Mohammad Shami,14,14,52.4,395,19,3/21,20.78,7.50,16.63,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,106,Ben Stokes,1,1,1,12,0,0/12,0.00,12.00,0.00,0,0
106,107,Dhawal Kulkarni,1,1,4,48,0,0/48,0.00,12.00,0.00,0,0
107,108,Shreyas Gopal,3,3,7,84,0,0/9,0.00,12.00,0.00,0,0
108,109,Kamlesh Nagarkoti,1,1,2,25,0,0/25,0.00,12.50,0.00,0,0
109,110,Navdeep Saini,2,2,4,52,0,0/25,0.00,13.00,0.00,0,0

In [5]:
bowling_stats.to_csv('bowling_stats.csv', index=False)